FROM centos:7

# ติดตั้ง Go
RUN yum install -y wget
RUN wget https://golang.org/dl/go1.21.6.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.21.6.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin

# ติดตั้ง GCC และ build tools
RUN yum groupinstall -y "Development Tools"

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build -o main .

CMD ["./main"]
